# run Xcode analyze and test actions
name: Xcode Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Analyze and run test
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Initialize environment
      uses: ./.github/actions/init
      with:
        certificate: ${{ secrets.CODE_SIGN_CERTIFICATE }}
        password: ${{ secrets.CODE_SIGN_PASSWORD }}

    - name: Xcode build action
      run: |
        xcodebuild build -scheme "Movie Archive" -configuration Debug
        xcodebuild build -scheme "Movie Archive" -configuration Release

    - name: Xcode analyze action
      run: xcodebuild analyze -scheme "Movie Archive"

    - name: Xcode test action
      run: xcodebuild test -scheme "Movie Archive"

    - name: Xcode docbuild action
      run: xcodebuild docbuild -scheme "Movie Archive"
